MVC02/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Mvc02.Services;
using MVC02.Data;
using MVC02.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MVC02.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly AuthService _auth;
        private readonly IHostingEnvironment _env;

        public AdminController(ApplicationDbContext context, AuthService auth, IHostingEnvironment env)
        {
            _context = context;
            _auth = auth;
            _env = env;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<UserAndRoles> usersWithRoles = await _auth.GetUsersWithRoles();
            return View(usersWithRoles);
        }

        public async Task<IActionResult> ManageRoles()
        {
            IEnumerable<UserAndRoles> usersWithRoles = await _auth.GetUsersWithRoles();
            return View(usersWithRoles);
        }

        public async Task<IActionResult> AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string role)
        {
            if (!await _auth.AddRole(role))
            {
                ModelState.AddModelError("RoleExist", "Rollen finns redan");
                return View();
            }
            return View();
        }

        public async Task<IActionResult> AddRoleForUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddRoleForUser(AddRoleVm addrole)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }
            else if (!await _auth.UserExist(addrole.Email))
            {
                ModelState.AddModelError("UserExist", "Användaren hittades inte");
                return View();
            }
            else if (!await _auth.RoleExists(addrole.Role))
            {
                ModelState.AddModelError("RoleExist", "Rollen hittades inte");
                return View();
            }
            else if (!await _auth.AddRoleToUser(addrole.Email, addrole.Role))
            {
                ModelState.AddModelError("CombinationExists", "Användaren har redan denna roll");
                return View();
            }
            return View("Success", addrole);
        }

        public async Task<IActionResult> EditRoles(string id)
        {
            return View();
        }

        public async Task<IActionResult> EditUserRoles(string id)
        {
            var viewModel = new EditUserRolesViewModel();

            viewModel.AllRoles = await _auth.GetRolesAsSelectListItems();
            viewModel.User = await _auth.GetUserById(id);
            viewModel.SelectedRoles = await _auth.GetUsersRole(viewModel.User);

            viewModel.Id = viewModel.User.Id;
            viewModel.Email = viewModel.User.Email;

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditUserRoles(EditUserRolesViewModel viewModel)
        {
            var user = await _auth.GetUserById(viewModel.Id);

            IEnumerable<string> oldRoles = _auth.GetUsersRole(user).Result;

            var rolesToDelete = oldRoles.Where(oldRoleName => viewModel.SelectedRoles.All(newRoleName => newRoleName != oldRoleName));

            await _auth.DeleteRole(user, rolesToDelete);
            //rolesToDelete.ToList().ForEach(x => _auth.DeleteRole(x))

            viewModel.SelectedRoles.ToList().ForEach( x =>  _ = _auth.AddRoleToUser(viewModel.Id, x).Result);

            

            //    ViewModel.AllRoles = await _auth.GetRolesAsSelectListItems();
            //    ViewModel.User = await _auth.GetUserById(id);
            //    ViewModel.SelectedRoles = await _auth.GetUsersRole(ViewModel.User);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult UploadImage([FromBody]string image)
        {
            System.Security.Claims.ClaimsPrincipal u = User;
            string fileNameWitPath = _env.WebRootPath + @"/images/" + _auth.GetUserId(User) + ".png";
            using (FileStream fs = new FileStream(fileNameWitPath, FileMode.Create))
            {
                using (BinaryWriter bw = new BinaryWriter(fs))
                {
                    byte[] data = Convert.FromBase64String(image);
                    bw.Write(data);
                    bw.Close();
                }
            }
            return Ok();
        }
    }
}

MVC02/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC02.Data;
using MVC02.Models.Entities;

namespace MVC02.Controllers
{
    //[Authorize(Roles ="Kung")]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
       
        public async Task<IActionResult> Index()
        {

                return View(await _context.Category.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Category category)
        {
            if( _context.Category.Any(x => x.Name == category.Name))
            {
                ModelState.AddModelError("Occupied", "The category is already defined");
            }
            else if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.Id == id);
        }
    }
}

MVC02/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC02.Models;

namespace MVC02.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ViewResult Success(Contact contact)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }

            return View("Success", contact);

        }

    }
}

MVC02/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mvc02.Services;
using MVC02.Data;
using MVC02.Models;
using MVC02.Models.ViewModels;


namespace MVC02.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly AuthService _auth;

        public ProductsController(ApplicationDbContext context, AuthService auth)
        {
            _context = context;
            _auth = auth;

        }

        // GET: Products
        public async Task<IActionResult> Index(int? id)
        {
            if (id.HasValue)
                return View(await _context.Product.Include(x => x.Category).Where(x => x.Category.Id == id).ToListAsync());

            else
            {
                var r = User.IsInRole("apa");
                var productList = _context.Product.Include(x => x.Category).Include(x => x.ProductsRoles).ToList();
                if (User.IsInRole("admin"))
                {
                    return View(productList);
                }
                var roleList = _auth.GetAllRoles().ToList();
                var userRoles = roleList;
                var userProductList = productList;
                foreach (var role in roleList)
                {
                    if (!User.IsInRole(role.Text))
                        userRoles = userRoles.Where(x => x != role).ToList();
                }

               foreach (var product in productList)
                {
                        bool ProductRoleMatchUserRole = false;
                    foreach (var role in userRoles)
                    {
                        foreach (var productRole in product.ProductsRoles)
                        {
                            if (productRole.RoleId == role.Value)
                                ProductRoleMatchUserRole = true;
                        }
                    }
                    if (!ProductRoleMatchUserRole)
                        userProductList = userProductList.Where(userProduct => userProduct != product).ToList();
                }
               
                return View(userProductList);
                //return View(await _context.Product.Include(x => x.Category).Include(x => x.ProductsRoles).Where(product => product.ProductsRoles.Any(role =>  User.IsInRole(role.RoleId.ToString()))).ToListAsync());
            }
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.Include(x => x.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            var viewModel = new CreateProductVm();
            viewModel.AllCategories = _context.Category.Select(category => new SelectListItem() { Text = category.Name, Value = category.Id.ToString() });
            viewModel.AllRoles = _auth.GetAllRoles();

            return View(viewModel);
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductVm vm) // [Bind("Id,Name,Price,CategoryId,ForSale,ProductsRoles")] 
        {


            if (ModelState.IsValid)
            {
                vm.Product.ProductsRoles = new List<ProductsRoles>();
                //List<string> xs = new List<string>();
                foreach (var role in vm.SelectedRoles)
                {
                    //xs.Add(role);
                    vm.Product.ProductsRoles.Add(new ProductsRoles { RoleId = role });
                }
                vm.SelectedRoles = new List<string>();
                _context.Add(vm.Product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(null);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            var viewModel = new CreateProductVm();
            viewModel.AllCategories = _context.Category.Select(category => new SelectListItem() { Text = category.Name, Value = category.Id.ToString() });
            viewModel.Product = product;

            return View(viewModel);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,CategoryId,ForSale")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.Include(x => x.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.Id == id);
        }
    }
}

MVC02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC02</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<body>
    @*<nav class="navbar  navbar-light bg-light">*@
        <nav class="navbar navbar-expand-lg navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MVC02</a>
            </div>
            <div class="navbar-collapse collapse" id="navbarNavDropdown">
                <ul class="nav navbar-nav ">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                    <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                    @*@if (User.IsInRole("admin"))
                    {*@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" asp-controller="Admin" asp-action="Index" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Admin" asp-action="Index">Display users and roles</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a asp-controller="Admin" asp-action="AddRole">Add new role</a></li>
                                <li><a asp-controller="Admin" asp-action="AddRoleForUser">Add role to user</a> </li>
                                <li><a asp-controller="Admin" asp-action="ManageRoles">Role manager</a> </li>
                            </ul>
                        </li>

                        @*}*@
                    <li><a asp-area="" asp-controller="Contact" asp-action="Index">Contact</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                </ul>
               
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>



    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - MVC02</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>